### ISSUE TITLE
Cannot Insert Inline Figures

### ISSUE THREAD

**Issue by ChenFengJR** [susam/texme#10] opened 2019-05-10 09:26 UTC
Hi Susam,
  I'm using your texme for self-rendering "Markdown+Tex". But I happen to find that I cannot load image with hyperlink either in the following two ways:
```html
![TAG](FIG_URL)
or
<div align="center">
  <img src="FIG_URL">
</div>
```
Is their any solution? Look forward to your reply.

**Comment by susam** [comment] 2020-09-27 09:48
Hi @ChenFengJR,

I was unable to reproduce the issue. If I save the following content in a file named, say, `foo.html`, and open it with Firefox 81 and Chrome 85, the output appears fine.

```html
<!DOCTYPE html><script src="https://cdn.jsdelivr.net/npm/texme@0.9.0"></script><textarea>

![TAG](https://i.imgur.com/UrJrpo1.png)

<div align="center">
  <img src="https://i.imgur.com/UrJrpo1.png">
</div>
```

Here is an example on JSFiddle that shows that the rendering looks fine: <https://jsfiddle.net/fecak021/>.

If you are still having this issue, would you please share a complete document that includes the `<script>` tag that loads TeXMe as well as the Markdown or HTML content, so that I can reproduce the issue?

**Comment by susam** [comment] 2022-10-09 00:41
Closing this issue because image rendering works fine with TeXMe.

**Closed by susam** 2022-10-09 00:41 UTC
Labels: question
